Page({
  data:{
    mytext:'First-WeChat-Mini-app'
  },
  onLoad:function(options){
    // 生命周期函数--监听页面加载
    console.log("执行onLoad");
    this.myfunction();
  },
    myfunction:function(){
    console.log("myfunction");
    },
  dxfunction:function(){
    console.log("执行dxfunction");
    this.setData({
mytext:'欢迎来到大喜杂货店'
    });
  }
})